export const SAVE_SEARCH_TERM = "SAVE_SEARCH_TERM";
export const SAVE_API_DATA = "SAVE_API_DATA";
export const UPDATE_ERROR = "UPDATE_ERROR";
export const UPDATE_PAGE_NUMBER = "UPDATE_PAGE_NUMBER";
export const UPDATE_MAX_RESULTS_NUMBER = "UPDATE_MAX_RESULTS_NUMBER";

export const SAVE_CURRENT_USER = "SAVE_CURRENT_USER";

export const SAVE_SINGLE_PROPERTY = "SAVE_SINGLE_PROPERTY";
